### ISSUE TITLE
Same issue with carthage and bitcode set to no

### ISSUE THREAD

**Issue by Vaseltior** [mxcl/OMGHTTPURLRQ#13]
https://github.com/mxcl/PromiseKit/issues/285

Hi, 

When I try to compile both of your projects using carthage, I get the following message :
```
target 'PMKwatchOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'watchos' 
```

The project is obviously configured in a way that bitcode is enable, but this occurs in two of your projects. Would you mind, when you have some time, to have a look at this? Thx

**Comment by mxcl** [comment]
We have looked at it and can't figure out a fix.

**Comment by nathanhosselton** [comment]
This should be resolved by the latest version of Carthage. If not, please feel free to reopen.

**Comment by Vaseltior** [comment]
Cool, Thx for answering.

2016-01-31 23:57 GMT+01:00 Nathan Hosselton <notifications@github.com>:

> This should be resolved by the latest version of Carthage. If not, please
> feel free to reopen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mxcl/OMGHTTPURLRQ/issues/13#issuecomment-177647626>.
>



-- 
Samuel GRAU
Mobile : + 33 (0) 6 79 39 38 47
