### ISSUE TITLE
GET method shouldn't add ? to URL if params are nil

### ISSUE THREAD

**Issue by rlaferla** [mxcl/OMGHTTPURLRQ#18]
Here's the proposed patch:

```
@implementation OMGHTTPURLRQ

+ (NSMutableURLRequest *)GET:(NSString *)urlString :(NSDictionary *)params error:(NSError **)error {
    if (params != nil) {
        id queryString = OMGFormURLEncode(params);
        if (queryString) urlString = [urlString stringByAppendingFormat:@"?%@", queryString];
    }
    id url = [NSURL URLWithString:urlString];
    if (!url) {
        if (error) *error = OMGInvalidURLErrorMake();
        return nil;
    }

    NSMutableURLRequest *rq = OMGMutableURLRequest();
    rq.HTTPMethod = @"GET";
    rq.URL = url;
    return rq;
}

```

**Comment by rherubin** [comment]
proposed patch to the OMGFormURLEncode.m file:

NSString *OMGFormURLEncode(NSDictionary *parameters) {
    if (parameters.count == 0)
        return nil;
    NSMutableString *queryString = [NSMutableString new];
    NSEnumerator *e = DoQueryMagic(nil, parameters).objectEnumerator;
    for (;;) {
        id const obj = e.nextObject;
        if (!obj) break;
        [queryString appendFormat:@"%@=%@&", enckey(obj), encval(e.nextObject)];
    }
    [queryString deleteCharactersInRange:NSMakeRange(queryString.length - 1, 1)];
    return queryString;
}

**Comment by jonasman** [comment]
+1
