### ISSUE TITLE
Problem when installing via Carthage

### ISSUE THREAD

**Issue by LinusU** [mxcl/OMGHTTPURLRQ#6]
I'm trying to install PromiseKit via Carthage but it fails with the following error.

**Output from Carthage**

```text
*** Fetching PromiseKit
*** Cloning OMGHTTPURLRQ
*** Checking out OMGHTTPURLRQ at "2.1.1"
*** Checking out starscream at "0.9.2"
*** Checking out PromiseKit at "1.2.4"
*** xcodebuild output can be found in /.../carthage-xcodebuild.0fWKf0.log
*** Building scheme "OMGHTTPURLRQ" in OMGHTTPURLRQ.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Last lines of `/.../carthage-xcodebuild.0fWKf0.log`**

```text
** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.1

=== BUILD TARGET OMGHTTPURLRQ OF PROJECT OMGHTTPURLRQ WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID <E2><80><9C>(null)<E2><80><9D> were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.1'
```

**Comment by mxcl** [comment]
Works for me. The code signing stuff is suspicious though, I've read people having problems with this sort of thing before on the Carthage issue tracker. May I request you take a look there and see if anything fits? The problem may well still be in PromiseKit or OMGHTTPURLRQ's Xcode settings but I can't verify it.

```sh
$ mkdir foo
$ cd foo/
$ echo 'github "mxcl/PromiseKit" > Cartfile 
$ carthage update
*** Cloning PromiseKit
*** Fetching OMGHTTPURLRQ
*** Checking out OMGHTTPURLRQ at "2.1.1"
*** Checking out PromiseKit at "1.2.4"
*** xcodebuild output can be found in /var/folders/9p/55y6r8hs3yz2qkhvf74gc0gh0000gn/T/carthage-xcodebuild.tvaQv8.log
*** Building scheme "OMGHTTPURLRQ" in OMGHTTPURLRQ.xcodeproj
*** Building scheme "PromiseKit" in PromiseKit.xcodeproj
$
```

**Comment by LinusU** [comment]
Same problem with latest version (`0.6.0`) and in a clean directory (copied and pasted your commands). I will have a look around the Carthage issues and see if I can find anything relevant.

**Comment by mxcl** [comment]
FYI https://github.com/Carthage/Carthage/issues/294

**Comment by arieljake** [comment]
I'm getting this too. And it's not related to Carthage#294 because I can't build target OMGHTTPURLRQ.

Errors says:

No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.

Could it be related to the team ID (null) part?

**Comment by mxcl** [comment]
I don't think this is a bug in OMGHTTPURLRQ, it's due to Carthage, and they seem to think the onus is on you to make it work: https://github.com/Carthage/Carthage/issues/235

I suggest CocoaPods until Carthage is mature.

**Comment by arieljake** [comment]
but I DO have a developer account, and two other projects are building fine through Carthage, so what setting inside this project is different that it doesn't work?

**Comment by mxcl** [comment]
I guess I'll have to dig deeper. I have no clue right now though.

**Comment by mxcl** [comment]
@arieljake you may want to chime in here: https://github.com/Carthage/Carthage/issues/370#issuecomment-77061510
